version: '3.8'

services:
  api:
    build: .
    container_name: house-price-api
    ports:
      - "8000:8000"
    volumes:
      - ./model.pkl:/app/model.pkl
      - ./feature_columns.pkl:/app/feature_columns.pkl
      - ./unique_locations.pkl:/app/unique_locations.pkl
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: house-price-streamlit
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge